# Adjust these URLs, users and passwords to your local MySQL setup.

# Auth DB (user accounts and password hashes only)
auth.jdbc.url=jdbc:mysql://localhost:3306/univ_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
auth.jdbc.user=root
auth.jdbc.password=Arh@m_1411

# ERP DB (students, instructors, courses, sections, enrollments, grades, settings)
erp.jdbc.url=jdbc:mysql://localhost:3306/univ_erp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
erp.jdbc.user=root
erp.jdbc.password=Arh@m_1411


